-- Voeg ontbrekende kolommen toe aan badges-tabel (indien ze nog niet bestaan)
ALTER TABLE badges ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE badges ADD COLUMN IF NOT EXISTS icon_url TEXT;
ALTER TABLE badges ADD COLUMN IF NOT EXISTS type VARCHAR(50);
ALTER TABLE badges ADD COLUMN IF NOT EXISTS category VARCHAR(50);
ALTER TABLE badges ADD COLUMN IF NOT EXISTS criteria TEXT;
ALTER TABLE badges ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE badges ADD COLUMN IF NOT EXISTS "order" INTEGER;
ALTER TABLE badges ADD COLUMN IF NOT EXISTS color VARCHAR(20);
ALTER TABLE badges ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE badges ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
