-- Voeg 25 unieke badges toe aan de badges-tabel
INSERT INTO badges (name, description, icon_url, type, category, color, is_active, "order") VALUES
('Starter', 'Maak je profiel compleet', 'https://img.icons8.com/color/48/000000/star--v1.png', 'milestone', 'profile', '#FFD700', true, 1),
('Early Bird', 'Log in voor 7:00 uur', 'https://img.icons8.com/color/48/000000/sunrise.png', 'activity', 'routine', '#FFA500', true, 2),
('Night Owl', 'Log in na 22:00 uur', 'https://img.icons8.com/color/48/000000/moon-symbol.png', 'activity', 'routine', '#4B0082', true, 3),
('First Workout', 'Voltooi je eerste workout', 'https://img.icons8.com/color/48/000000/dumbbell.png', 'milestone', 'workout', '#4ade80', true, 4),
('Consistency', 'Doe 3 dagen achter elkaar een workout', 'https://img.icons8.com/color/48/000000/calendar-3.png', 'streak', 'workout', '#00BFFF', true, 5),
('Streak Master', 'Doe 7 dagen achter elkaar een workout', 'https://img.icons8.com/color/48/000000/fire-element.png', 'streak', 'workout', '#FF4500', true, 6),
('Socializer', 'Volg je eerste gebruiker', 'https://img.icons8.com/color/48/000000/add-user-group-man-man.png', 'social', 'community', '#8A2BE2', true, 7),
('Popular', 'Krijg 5 volgers', 'https://img.icons8.com/color/48/000000/crowd.png', 'social', 'community', '#FF69B4', true, 8),
('Commentator', 'Plaats je eerste reactie', 'https://img.icons8.com/color/48/000000/comments.png', 'activity', 'community', '#20B2AA', true, 9),
('Motivator', 'Geef 5 likes', 'https://img.icons8.com/color/48/000000/facebook-like.png', 'activity', 'community', '#32CD32', true, 10),
('Sharer', 'Deel je eerste workout', 'https://img.icons8.com/color/48/000000/share.png', 'activity', 'workout', '#1E90FF', true, 11),
('Explorer', 'Bekijk 10 verschillende profielen', 'https://img.icons8.com/color/48/000000/compass.png', 'activity', 'profile', '#FF6347', true, 12),
('Goal Setter', 'Stel een fitnessdoel in', 'https://img.icons8.com/color/48/000000/goal.png', 'milestone', 'profile', '#FFD700', true, 13),
('Goal Achiever', 'Behaal een fitnessdoel', 'https://img.icons8.com/color/48/000000/trophy.png', 'milestone', 'profile', '#DAA520', true, 14),
('First Comment', 'Ontvang je eerste reactie', 'https://img.icons8.com/color/48/000000/speech-bubble.png', 'social', 'community', '#00CED1', true, 15),
('First Like', 'Ontvang je eerste like', 'https://img.icons8.com/color/48/000000/filled-like.png', 'social', 'community', '#DC143C', true, 16),
('First Follower', 'Ontvang je eerste volger', 'https://img.icons8.com/color/48/000000/add-user-group-woman-man.png', 'social', 'community', '#FF8C00', true, 17),
('First Post', 'Maak je eerste post', 'https://img.icons8.com/color/48/000000/edit.png', 'activity', 'community', '#4682B4', true, 18),
('Active Week', '7 dagen actief in 1 week', 'https://img.icons8.com/color/48/000000/week-view.png', 'streak', 'workout', '#00FF7F', true, 19),
('Active Month', '30 dagen actief in 1 maand', 'https://img.icons8.com/color/48/000000/month-view.png', 'streak', 'workout', '#9932CC', true, 20),
('Feedback Giver', 'Geef feedback op een workout', 'https://img.icons8.com/color/48/000000/feedback.png', 'activity', 'community', '#B22222', true, 21),
('Feedback Receiver', 'Ontvang feedback op een workout', 'https://img.icons8.com/color/48/000000/feedback-hub.png', 'activity', 'community', '#228B22', true, 22),
('Challenge Starter', 'Start je eerste challenge', 'https://img.icons8.com/color/48/000000/flag.png', 'activity', 'challenge', '#FF4500', true, 23),
('Challenge Winner', 'Win een challenge', 'https://img.icons8.com/color/48/000000/medal2.png', 'milestone', 'challenge', '#FFD700', true, 24),
('Community Helper', 'Help een andere gebruiker', 'https://img.icons8.com/color/48/000000/helping-hand.png', 'social', 'community', '#00BFFF', true, 25);
