-- Migration: Add fitness-related fields to profiles table
-- This enables storing onboarding data and workout preferences in the user's profile

-- Add fitness level (beginner, intermediate, advanced)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS fitness_level TEXT
CHECK (fitness_level IN ('beginner', 'intermediate', 'advanced'));

-- Add age for volume/intensity adjustments
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS age INTEGER
CHECK (age >= 13 AND age <= 120);

-- Add gender (already exists from previous migration, but ensuring it's there)
-- ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;

-- Add event type for event-based training (hyrox, spartan, marathon, etc.)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS event_type TEXT;

-- Add limitations/injuries (knee, shoulder, back, etc.)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS limitations TEXT[] DEFAULT '{}';

-- Add available equipment (barbell, dumbbells, kettlebell, etc.)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS available_equipment TEXT[] DEFAULT '{}';

-- Add preferred workout duration in minutes
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS preferred_duration INTEGER
CHECK (preferred_duration >= 5 AND preferred_duration <= 180);

-- Add preferred workout styles (emom, circuit, traditional, etc.)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS preferred_workout_styles TEXT[] DEFAULT '{}';

-- Add preferred muscle groups
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS preferred_muscles TEXT[] DEFAULT '{}';

-- Add training frequency days (monday, tuesday, etc.)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS frequency_days TEXT[] DEFAULT '{}';

-- Add preferred training time (morning, afternoon, evening)
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS preferred_time TEXT;

-- Add onboarding completion tracking
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMPTZ;

-- Add last workout generation timestamp
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS last_workout_generated_at TIMESTAMPTZ;

-- Add total workouts generated count
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS total_workouts_generated INTEGER DEFAULT 0;

-- Create index for faster queries on fitness level
CREATE INDEX IF NOT EXISTS profiles_fitness_level_idx ON profiles(fitness_level);

-- Create index for faster queries on onboarding status
CREATE INDEX IF NOT EXISTS profiles_onboarding_completed_idx ON profiles(onboarding_completed);

-- Add comment to document the new fields
COMMENT ON COLUMN profiles.fitness_level IS 'User fitness level: beginner, intermediate, or advanced';
COMMENT ON COLUMN profiles.age IS 'User age for volume/intensity adjustments';
COMMENT ON COLUMN profiles.event_type IS 'Event type for event-based training (hyrox, spartan, marathon, etc.)';
COMMENT ON COLUMN profiles.limitations IS 'Physical limitations or injuries (knee, shoulder, back, etc.)';
COMMENT ON COLUMN profiles.available_equipment IS 'Equipment available to user (barbell, dumbbells, kettlebell, etc.)';
COMMENT ON COLUMN profiles.preferred_duration IS 'Preferred workout duration in minutes';
COMMENT ON COLUMN profiles.preferred_workout_styles IS 'Preferred workout styles (emom, circuit, traditional, etc.)';
COMMENT ON COLUMN profiles.preferred_muscles IS 'Preferred muscle groups to target';
COMMENT ON COLUMN profiles.frequency_days IS 'Training frequency days (monday, tuesday, etc.)';
COMMENT ON COLUMN profiles.preferred_time IS 'Preferred training time (morning, afternoon, evening)';
COMMENT ON COLUMN profiles.onboarding_completed IS 'Whether user has completed onboarding';
COMMENT ON COLUMN profiles.onboarding_completed_at IS 'Timestamp when onboarding was completed';
COMMENT ON COLUMN profiles.last_workout_generated_at IS 'Last time user generated a workout';
COMMENT ON COLUMN profiles.total_workouts_generated IS 'Total number of workouts generated by user';
